name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPACECORE_BINARY: ipfs-spacecore

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build Spacecore plugin
        run: |
          go build -o ${{ env.SPACECORE_BINARY }}

      - name: Package Spacecore for linux
        run: zip sc-linux-amd64.zip sc-linux-amd64/${{ env.SPACECORE_BINARY }}

      - name: Package Spacecore for mac
        run: zip sc-darwin-arm64.zip sc-darwin-arm64/${{ env.SPACECORE_BINARY }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sc-linux-amd64.zip
          path: sc-linux-amd64.zip

      - name: Upload Artifacts Mac
        uses: actions/upload-artifact@v2
        with:
          name: sc-darwin-arm64.zip
          path: sc-darwin-arm64.zip
