name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPACECORE_BINARY: ipfs-spacecore

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build binary
        run: |
          go build -o ${{ env.SPACECORE_BINARY }}

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.SPACECORE_BINARY }}

      - name: Upload release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.SPACECORE_BINARY }}
          asset_name: ${{ env.SPACECORE_BINARY }}
          asset_content_type: application/octet-stream
          token: ${{ secrets.GITHUB_TOKEN }}

